version: '3'
services:
  notaprod:
    image: notaorg/nota-prod:latest
    command: node bin/www
    ports:
     - "3000:3000" # host:container
     #- "27017:27017"
     #- "27018:27018"
    environment:
      - NODE_ENV=production
      - DATABASEURI=mongodb://${dbUsernameProd}:${dbPasswordProd}@${dbAddress}/${dbName}
      - ACTIVATE_EMAIL=${ACTIVATE_EMAIL} # string value to turn on emails
      - RESET_URI=${RESET_URI} # uri to tell user where to reset their password
      - FROM_HEADER=${FROM_HEADER} # from header, shows subject and sender address
      - MAILGUN_API_KEY=${MAILGUN_API_KEY} # mailgun api
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN} # mailgun key
    container_name: notaprod # restarts container unless we explicitly stop it
    restart: unless-stopped
